version: "3"

services:
  kms:
    container_name: local-kms-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - .:/go/src/github.com/nsmithuk/local-kms
    - ./init:/init
    ports:
    - 8688:8688
